"""empty message

Revision ID: 712dec921e8f
Revises: 0bd0dca2da18
Create Date: 2020-12-28 15:23:23.039171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712dec921e8f'
down_revision = '0bd0dca2da18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
