"""empty message

Revision ID: 819cf7490fe1
Revises: 712dec921e8f
Create Date: 2020-12-29 10:34:49.258786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819cf7490fe1'
down_revision = '712dec921e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
